version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10 
    commands:
      - echo install step...
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Compiling application...
      - npm run build
  post_build:
    commands:
      # - mkdir ./dist/server/.ebextensions/
      # - cp ./infrastructure/proxy.config ./dist/server/.ebextensions/proxy.config
artifacts:
  secondary-artifacts:
    artifact1:
      base-directory: ./dist
      files:
        - '**/*'